In [2]:
# !pip install pandas

In [3]:
import pandas as pd

In [6]:
info  = {
    "Name" : ["Sanjeev kumar","Anshu kumar" , "Dev Kumar"],
    "CGPA" : [8.5 , 9.0 ,  9.4]
}
# DataFrame
data = pd.DataFrame(info)
data

            Name  CGPA
0  Sanjeev kumar   8.5
1    Anshu kumar   9.0
2      Dev Kumar   9.4

In [8]:
# Series

val = [1,2,3,4,5,6];

s = pd.Series(val)
print(s[0]) #access

1

In [9]:
# labeling

l = pd.Series([22,23,24,25], index=["Adam","Eve","Bob","Chalie"])

In [10]:
l

Adam      22
Eve       23
Bob       24
Chalie    25
dtype: int64

In [11]:
l["Bob"]

np.int64(24)

In [12]:
# Series Properties

ld = pd.Series([22,23,24,25,"abc"], index=["Adam","Eve","Bob","Chalie",35])
ld

Adam       22
Eve        23
Bob        24
Chalie     25
35        abc
dtype: object

In [14]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [15]:
changed_s1 = s1.drop(0)

In [16]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
changed_s1

1    2
2    3
3    4
4    5
dtype: int64

In [19]:
# DataFrame

df = pd.DataFrame([["Sanjev kumar" , 25],["Anshu kumar" , 17],["Sonu kumar" , 18]],columns=["Name", "age"])
df

           Name  age
0  Sanjev kumar   25
1   Anshu kumar   17
2    Sonu kumar   18

In [22]:
import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])

df2 = pd.DataFrame(np_arr,columns=["A","B","C"])
df2

   A  B  C
0  1  2  3
1  4  5  6

In [23]:
df = pd.read_csv("employee_data.csv")
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [24]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [25]:
df.sample()

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000

In [26]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [27]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [29]:
df.shape

(10, 5)

In [30]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64