In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [5]:
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [6]:
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [7]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [9]:
df.isna().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [12]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [16]:

cleaned_data = df.copy()

age_mean = cleaned_data["age"].mean()

cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [19]:


cleaned_data["age"].dtype

dtype('float64')

In [21]:
cleaned_data["age"] = cleaned_data["age"].astype("int64").copy()

In [22]:
cleaned_data

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith   32  Canada   Female  62000.0
3    3          Alex   32     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      NaN
5    5        Li Wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    Ahmed Khan   38     NaN     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz   32  Mexico     Male  45000.0
10  10   Emily Davis   31     USA      NaN  58000.0

In [24]:
names = cleaned_data["name"].str.split(" ")
names

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [26]:
cleaned_data["country"].str.contains("india" , case = False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [43]:
# Feature Engineering

df2 = df.copy()

df2


# apply 

df2["tax"] =  df2["income"].apply(lambda x : "20%" if x <= 50000  else  "10%")

gender_map = { "Male" : "M" , "Female" : "F" , "Unknown" : "U"}


df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income  = df["income"] * 1.1)

df2["country"] = df2["country"].replace("USA" , "UA")

df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      UA      M  55000.0  10%     60500.0
1    1      John Doe  29.0      UA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  10%     68200.0
3    3          Alex   NaN      UA      U  47000.0  20%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  10%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  10%     74800.0
8    8    Rachel Lee  29.0      UA      F  62000.0  10%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%     49500.0
10  10   Emily Davis  31.0      UA    NaN  58000.0  10%     63800.0

In [46]:
df2.columns = ["Id", "Name", "Age","Country","Gender","Salary","Tax","New_Salary"]

In [47]:
df2

    Id          Name   Age Country Gender   Salary  Tax  New_Salary
0    1      John Doe  29.0      UA      M  55000.0  10%     60500.0
1    1      John Doe  29.0      UA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  10%     68200.0
3    3          Alex   NaN      UA      U  47000.0  20%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  10%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  10%     74800.0
8    8    Rachel Lee  29.0      UA      F  62000.0  10%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%     49500.0
10  10   Emily Davis  31.0      UA    NaN  58000.0  10%     63800.0

In [60]:
sorted_values = df2.sort_values(["Salary", "Age"] , ascending=False)

sorted_values = sorted_values.sort_index()
# sorted_values.reset_index()

sorted_values["Ranking"] = sorted_values["Salary"].rank(ascending = False , method = "dense")

sorted_values

    Id          Name   Age Country Gender   Salary  Tax  New_Salary  Ranking
0    1      John Doe  29.0      UA      M  55000.0  10%     60500.0      5.0
1    1      John Doe  29.0      UA      M  55000.0  10%     60500.0      5.0
2    2    Jane Smith   NaN  Canada      F  62000.0  10%     68200.0      3.0
3    3          Alex   NaN      UA      U  47000.0  20%     51700.0      7.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      6.0
6    6           NaN  45.0   India      F  73000.0  10%     80300.0      1.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  10%     74800.0      2.0
8    8    Rachel Lee  29.0      UA      F  62000.0  10%     68200.0      3.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%     49500.0      8.0
10  10   Emily Davis  31.0      UA    NaN  58000.0  10%     63800.0      4.0

In [61]:
#  task to shift the id to the last 

df3  = df.copy()

In [65]:

new_col_order = [ col for col in df3.columns if col != "id"] + ["id"]

print(new_col_order)

['name', 'age', 'country', 'gender', 'income', 'id']

In [69]:
df3[new_col_order]

df3.columns = new_col_order

df3

    name           age  country  gender   income       id
0      1      John Doe     29.0     USA     Male  55000.0
1      1      John Doe     29.0     USA     Male  55000.0
2      2    Jane Smith      NaN  Canada   Female  62000.0
3      3          Alex      NaN     USA  Unknown  47000.0
4      4  Maria Garcia     34.0   Spain   Female      NaN
5      5        Li Wei     27.0   China     Male  51000.0
6      6           NaN     45.0   India   Female  73000.0
7      7    Ahmed Khan     38.0     NaN     Male  68000.0
8      8    Rachel Lee     29.0     USA   Female  62000.0
9      9   Carlos Ruiz      NaN  Mexico     Male  45000.0
10    10   Emily Davis     31.0     USA      NaN  58000.0