In [1]:
import pandas as pd

In [6]:
df_customer = pd.DataFrame({

    "customer_id" : [1,2,3,4],
    "name" : ["sam" ,"Dam", "Jam", "Tom"]
})
df_customer

   customer_id name
0            1  sam
1            2  Dam
2            3  Jam
3            4  Tom

In [7]:
df_orders = pd.DataFrame({
    "order_id" : [101,102,103,104],
    "customer_id" : [2,1,4,5],
    "amount" : [200,300,500,100]
})

df_orders

   order_id  customer_id  amount
0       101            2     200
1       102            1     300
2       103            4     500
3       104            5     100

In [5]:
pd.merge(df_customer, df_orders,on="customer_id")

   customer_id name  order_id  amount
0            1  sam       102     300
1            2  Dam       101     200
2            4  Tom       103     500

In [8]:
pd.merge(df_customer,df_orders,on="customer_id" , how="left")

   customer_id name  order_id  amount
0            1  sam     102.0   300.0
1            2  Dam     101.0   200.0
2            3  Jam       NaN     NaN
3            4  Tom     103.0   500.0

In [9]:
pd.merge(df_customer,df_orders,on="customer_id" , how="right")

   customer_id name  order_id  amount
0            2  Dam       101     200
1            1  sam       102     300
2            4  Tom       103     500
3            5  NaN       104     100

In [11]:
pd.merge(df_customer,df_orders,on="customer_id" , how="inner")

   customer_id name  order_id  amount
0            1  sam       102     300
1            2  Dam       101     200
2            4  Tom       103     500

In [12]:
pd.merge(df_customer,df_orders,on="customer_id" , how="outer")

   customer_id name  order_id  amount
0            1  sam     102.0   300.0
1            2  Dam     101.0   200.0
2            3  Jam       NaN     NaN
3            4  Tom     103.0   500.0
4            5  NaN     104.0   100.0