In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "country" : [ "USA","USA","INDIA","INDIA"],
    "year" : [2020,2021,2020,2021],
    "sales" : [100,120,90,110],
    "profit" : [20,25,18,22]
})

In [3]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   INDIA  2020     90      18
3   INDIA  2021    110      22

In [13]:
melted_df = df.melt(

    id_vars=["country", "year"],
    value_vars=["sales", "profit"],
    var_name="metrics",
    value_name="value",

);

melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   INDIA  2020   sales     90
3   INDIA  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   INDIA  2020  profit     18
7   INDIA  2021  profit     22

In [18]:
orginal = melted_df.pivot(
    index = ["country","year"],
    columns = "metrics",
    values = "value",
)

In [19]:
orginal

metrics       profit  sales
country year
INDIA   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [26]:
df2 = pd.read_csv("employee_data.csv")
df2

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [27]:
df2.plot(kind ="scatter" , x = "Age", y = "Salary")

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.