In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("employee_data.csv")

In [5]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [6]:
df2 = df.copy()

In [7]:
df = df2.drop_duplicates()

In [8]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [9]:
df2 = df2.fillna(0)

In [10]:
df2

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [11]:
df2 = df2.sort_values("Salary")

In [12]:
df2

   ID     Name  Age Department  Salary
7   8   Hannah   26  Marketing   47000
2   3  Charlie   28    Finance   48000
5   6    Frank   29    Finance   50000
0   1    Alice   25         HR   55000
9  10    Julia   30    Finance   60000
4   5      Eva   38         IT   65000
1   2      Bob   32         IT   72000
8   9      Ian   35         IT   75000
6   7    Grace   41         HR   82000
3   4    David   45  Marketing   91000

In [13]:
df2 = df2.reset_index(drop = True)

In [14]:
df2

   ID     Name  Age Department  Salary
0   8   Hannah   26  Marketing   47000
1   3  Charlie   28    Finance   48000
2   6    Frank   29    Finance   50000
3   1    Alice   25         HR   55000
4  10    Julia   30    Finance   60000
5   5      Eva   38         IT   65000
6   2      Bob   32         IT   72000
7   9      Ian   35         IT   75000
8   7    Grace   41         HR   82000
9   4    David   45  Marketing   91000

In [15]:
df2.to_csv("sorted_data.csv")